
version: '3.8'
services:
  # rust-log-processing:
  #   image: mcr.microsoft.com/devcontainers/rust:0-1-bullseye
  #   volumes:
  #     - ..:/workspaces:cached
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - seccomp:unconfined
  #   command: /bin/sh -c "while sleep 1000; do :; done"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  # jaeger:
  #   image: jaegertracing/all-in-one:1.42
  #   ports:
  #     - 5775:5775
  #     - 6831:6831
  #     - 6832:6832
  #     - 5778:5778
  #     - 16686:16686
  #     - 14268:14268
  #     - 14250:14250
  #     - 9411:9411
  #   environment:
  #     COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  #     COLLECTOR_OTLP_ENABLED: true
